import type { ruRU } from '@clerk/localizations'

type LocalizationResource = typeof ruRU

export const hyAM: LocalizationResource = {
  locale: 'hy-AM',
  backButton: 'Հետ',
  dividerText: 'կամ',
  formButtonPrimary: 'Շարունակել',
  formButtonPrimary__verify: 'Հաստատել',
  formFieldAction__forgotPassword: 'Մոռացե՞լ եք գաղտնաբառը',
  formFieldError__matchingPasswords: 'Գաղտնաբառերը համընկնում են',
  formFieldError__notMatchingPasswords: 'Գաղտնաբառերը չեն համընկնում',
  formFieldError__verificationLinkExpired: 'Հաստատման հղման ժամկետը լրացել է',
  formFieldHintText__optional: 'Կամընտիր',
  formFieldInputPlaceholder__emailAddress: 'Մուտքագրեք էլ. հասցեն',
  formFieldInputPlaceholder__emailAddress_username: 'Մուտքագրեք էլ. հասցեն կամ օգտանունը',
  formFieldInputPlaceholder__password: 'Մուտքագրեք գաղտնաբառը',
  formFieldInputPlaceholder__firstName: 'Անուն',
  formFieldInputPlaceholder__lastName: 'Ազգանուն',
  formFieldInputPlaceholder__backupCode: 'Պահուստային կոդ',
  formFieldLabel__emailAddress: 'Էլ. հասցե',
  formFieldLabel__emailAddress_username: 'Էլ. հասցե կամ օգտանուն',
  formFieldLabel__firstName: 'Անուն',
  formFieldLabel__lastName: 'Ազգանուն',
  formFieldLabel__password: 'Գաղտնաբառ',
  formFieldLabel__newPassword: 'Նոր գաղտնաբառ',
  formFieldLabel__confirmPassword: 'Հաստատել գաղտնաբառը',
  formFieldLabel__username: 'Օգտանուն',
  formFieldLabel__phoneNumber: 'Հեռախոսահամար',
  formFieldLabel__backupCode: 'Պահուստային կոդ',
  formFieldLabel__role: 'Դեր',
  formFieldLabel__signOutOfOtherSessions: 'Դուրս գալ մյուս սեսիաներից',
  socialButtonsBlockButton: '{{provider|titleize}}-ով շարունակել',
  paginationButton__next: 'Հաջորդ',
  paginationButton__previous: 'Նախորդ',
  signIn: {
    start: {
      title: 'Մուտք «{{applicationName}}»',
      titleCombined: 'Շարունակել «{{applicationName}}»',
      subtitle: '«{{applicationName}}» շարունակելու համար',
      actionText: 'Հաշիվ չունե՞ք',
      actionLink: 'Գրանցվել',
      actionLink__use_email: 'Օգտագործել էլ. հասցե',
      actionLink__use_phone: 'Օգտագործել հեռախոսահամար',
      actionLink__use_username: 'Օգտագործել օգտանուն',
      actionLink__use_passkey: 'Օգտագործել անցաբանալի',
    },
    password: {
      title: 'Մուտքագրեք գաղտնաբառը',
      subtitle: '«{{applicationName}}» շարունակելու համար',
      actionLink: 'Օգտագործել այլ մեթոդ',
    },
    emailCode: {
      title: 'Ստուգեք ձեր էլ. փոստը',
      subtitle: '«{{applicationName}}» շարունակելու համար',
      formTitle: 'Հաստատման կոդ',
      resendButton: 'Կոդ չստացա՞ք։ Կրկին ուղարկել',
    },
    emailLink: {
      title: 'Ստուգեք ձեր էլ. փոստը',
      subtitle: '«{{applicationName}}» շարունակելու համար',
      formTitle: 'Հաստատման հղում',
      formSubtitle: 'Օգտագործեք էլ. փոստով ուղարկված հղումը',
      resendButton: 'Հղում չստացա՞ք։ Կրկին ուղարկել',
      loading: { title: 'Մուտք եղեք...', subtitle: 'Կվերահղվեք շուտով' },
      verified: { title: 'Մուտքը հաջողված է', subtitle: 'Կվերահղվեք շուտով' },
      unusedTab: { title: 'Ներդիրը կարող եք փակել' },
    },
    forgotPassword: {
      title: 'Վերականգնել գաղտնաբառը',
      subtitle: 'Գաղտնաբառը վերականգնելու համար',
      formTitle: 'Վերականգնման կոդ',
      resendButton: 'Կրկին ուղարկել կոդը',
    },
    forgotPasswordAlternativeMethods: {
      title: 'Մոռացե՞լ եք գաղտնաբառը',
      blockButton__resetPassword: 'Վերականգնել գաղտնաբառը',
      label__alternativeMethods: 'Կամ մուտք գործեք այլ կերպ',
    },
    resetPassword: {
      title: 'Վերականգնել գաղտնաբառը',
      formButtonPrimary: 'Վերականգնել գաղտնաբառը',
      successMessage: 'Գաղտնաբառը հաջողությամբ փոխվեց։ Մուտք եղեք...',
      requiredMessage: 'Անվտանգության նկատառումներով անհրաժեշտ է վերականգնել գաղտնաբառը։',
    },
    alternativeMethods: {
      title: 'Օգտագործել այլ մեթոդ',
      subtitle: 'Խնդիրներ կա՞ն։ Կարող եք օգտագործել այլ մեթոդ',
      actionText: 'Ոչ մեկը հարմար չէ՞',
      actionLink: 'Օգնություն',
      blockButton__emailCode: 'Ուղարկել կոդ {{identifier}}',
      blockButton__emailLink: 'Ուղարկել հղում {{identifier}}',
      blockButton__password: 'Մուտք գաղտնաբառով',
      blockButton__phoneCode: 'Ուղարկել կոդ {{identifier}}',
      blockButton__backupCode: 'Օգտագործել պահուստային կոդ',
      blockButton__totp: 'Օգտագործել authenticator հավելվածը',
    },
    noAvailableMethods: {
      title: 'Հնարավոր չէ մուտք գործել',
      subtitle: 'Սխալ է տեղի ունեցել',
      message: 'Մուտք հնարավոր չէ։ Հասանելի նույնականացման գործոններ չկան։',
    },
  },
  signUp: {
    start: {
      title: 'Ստեղծել հաշիվ',
      titleCombined: 'Ստեղծել հաշիվ',
      subtitle: '«{{applicationName}}» շարունակելու համար',
      subtitleCombined: '«{{applicationName}}» շարունակելու համար',
      actionText: 'Հաշիվ արդեն ունե՞ք',
      actionLink: 'Մուտք գործել',
    },
    continue: {
      title: 'Լրացրեք բոլոր դաշտերը',
      subtitle: '«{{applicationName}}» շարունակելու համար',
      actionText: 'Հաշիվ արդեն ունե՞ք',
      actionLink: 'Մուտք գործել',
    },
    emailCode: {
      title: 'Հաստատեք ձեր էլ. հասցեն',
      subtitle: '«{{applicationName}}» շարունակելու համար',
      formTitle: 'Հաստատման կոդ',
      formSubtitle: 'Մուտքագրեք էլ. փոստով ուղարկված կոդը',
      resendButton: 'Կոդ չստացա՞ք։ Կրկին ուղարկել',
    },
    emailLink: {
      title: 'Հաստատեք ձեր էլ. հասցեն',
      subtitle: '«{{applicationName}}» շարունակելու համար',
      formTitle: 'Հաստատման հղում',
      formSubtitle: 'Օգտագործեք էլ. փոստով ուղարկված հղումը',
      resendButton: 'Հղում չստացա՞ք։ Կրկին ուղարկել',
      loading: { title: 'Մուտք եղեք...' },
      verified: { title: 'Մուտքը հաջողված է' },
      verifiedSwitchTab: {
        title: 'Էլ. հասցեն հաստատված է',
        subtitle: 'Վերադարձեք նոր ներդիրին շարունակելու համար',
        subtitleNewTab: 'Վերադարձեք նախկին ներդիրին շարունակելու համար',
      },
    },
    phoneCode: {
      title: 'Հաստատեք ձեր հեռախոսը',
      subtitle: '«{{applicationName}}» շարունակելու համար',
      formTitle: 'Հաստատման կոդ',
      formSubtitle: 'Մուտքագրեք հեռախոսով ուղարկված կոդը',
      resendButton: 'Կոդ չստացա՞ք։ Կրկին ուղարկել',
    },
  },
  userButton: {
    action__manageAccount: 'Կառավարել հաշիվը',
    action__signOut: 'Դուրս գալ',
    action__signOutAll: 'Դուրս գալ բոլոր հաշիվներից',
    action__addAccount: 'Ավելացնել հաշիվ',
  },
  userProfile: {
    start: {
      headerTitle__account: 'Հաշիվ',
      headerTitle__security: 'Անվտանգություն',
    },
    profilePage: {
      title: 'Պրոֆիլ',
      imageFormTitle: 'Պրոֆիլի նկար',
      imageFormSubtitle: 'Վերբեռնել նկար',
      imageFormDestructiveActionSubtitle: 'Հեռացնել նկարը',
      fileDropAreaHint: 'JPG, PNG, GIF, WebP, մինչև 10 ՄԲ',
      successMessage: 'Պրոֆիլը թարմացվեց',
    },
    formButtonPrimary__save: 'Պահել',
    formButtonReset: 'Չեղարկել',
  },
  unstable__errors: {
    form_identifier_not_found: 'Այս տվյալներով հաշիվ չի գտնվել։',
    form_password_or_identifier_incorrect: 'Գաղտնաբառը կամ էլ. հասցեն սխալ է։ Փորձեք կրկին։',
    form_identifier_exists__email_address: 'Այս էլ. հասցեն արդեն օգտագործվում է։ Փորձեք այլ հասցե։',
    form_param_format_invalid__email_address: 'Մուտքագրեք վավեր էլ. հասցե։',
    form_param_format_invalid__phone_number: 'Հեռախոսահամարը պետք է լինի վավեր միջազգային ձևաչափով։',
    form_password_not_strong_enough: 'Գաղտնաբառը բավականաչափ ուժեղ չէ։',
    form_password_pwned: 'Այս գաղտնաբառը բացահայտվել է տվյալների արտահոսքի ժամանակ։ Օգտագործեք այլ գաղտնաբառ։',
    captcha_invalid: 'Անվտանգության ստուգումը ձախողվեց։ Թարմացրեք էջը և կրկին փորձեք։',
    session_exists: 'Դուք արդեն մուտք եք գործել։',
    passwordComplexity: {
      sentencePrefix: 'Ձեր գաղտնաբառը պետք է պարունակի',
      minimumLength: '{{length}} կամ ավելի նիշ',
      maximumLength: '{{length}}-ից պակաս նիշ',
      requireLowercase: 'փոքրատառ տառ',
      requireUppercase: 'մեծատառ տառ',
      requireNumbers: 'թիվ',
      requireSpecialCharacter: 'հատուկ նիշ',
    },
  },
}
